inherit_from:
  - rubocop.yml
  - rubocop_rails.yml
  - rubocop_rspec.yml
  - rubocop_rake.yml
  - rubocop_performance.yml
  - rubocop_thread_safety.yml
  - rubocop_i18n.yml

RailsI18n/DecorateString:
  Enabled: false

